package com.havrylyuk.weather.dao;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ormCityDaoConfig;
    private final DaoConfig ormWeatherDaoConfig;

    private final OrmCityDao ormCityDao;
    private final OrmWeatherDao ormWeatherDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ormCityDaoConfig = daoConfigMap.get(OrmCityDao.class).clone();
        ormCityDaoConfig.initIdentityScope(type);

        ormWeatherDaoConfig = daoConfigMap.get(OrmWeatherDao.class).clone();
        ormWeatherDaoConfig.initIdentityScope(type);

        ormCityDao = new OrmCityDao(ormCityDaoConfig, this);
        ormWeatherDao = new OrmWeatherDao(ormWeatherDaoConfig, this);

        registerDao(OrmCity.class, ormCityDao);
        registerDao(OrmWeather.class, ormWeatherDao);
    }
    
    public void clear() {
        ormCityDaoConfig.clearIdentityScope();
        ormWeatherDaoConfig.clearIdentityScope();
    }

    public OrmCityDao getOrmCityDao() {
        return ormCityDao;
    }

    public OrmWeatherDao getOrmWeatherDao() {
        return ormWeatherDao;
    }

}
