package com.havrylyuk.weather.dao;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ORM_CITY".
 */
@Entity
public class OrmCity {

    @Id
    private Long _id;
    private String city_name;
    private String region;
    private String country;
    private Double lat;
    private Double lon;

    @Generated
    public OrmCity() {
    }

    public OrmCity(Long _id) {
        this._id = _id;
    }

    @Generated
    public OrmCity(Long _id, String city_name, String region, String country, Double lat, Double lon) {
        this._id = _id;
        this.city_name = city_name;
        this.region = region;
        this.country = country;
        this.lat = lat;
        this.lon = lon;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public String getCity_name() {
        return city_name;
    }

    public void setCity_name(String city_name) {
        this.city_name = city_name;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Double getLon() {
        return lon;
    }

    public void setLon(Double lon) {
        this.lon = lon;
    }

}
